version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./.persist/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - backend-1
      - backend-2
      - backend-3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #    command: [nginx-debug, '-g', 'daemon off;']

  backend-1:
    image: jpa:latest
    restart: on-failure
    container_name: backend-1
    ports:
      - 8081:8080
    depends_on:
      - mysql
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/test
      HOSTNAME: backend-1
      CONNECTION_TIMEOUT: 10000
      MIN_CONN_IDLE: 20

  backend-2:
    image: jpa:latest
    restart: on-failure
    container_name: backend-2
    ports:
      - 8082:8080
    depends_on:
      - mysql
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/test
      HOSTNAME: backend-2
      CONNECTION_TIMEOUT: 10000
      MIN_CONN_IDLE: 20

  backend-3:
    image: jpa:latest
    restart: on-failure
    container_name: backend-3
    ports:
      - 8083:8080
    depends_on:
      - mysql
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/test
      HOSTNAME: backend-3
      CONNECTION_TIMEOUT: 10000
      MIN_CONN_IDLE: 20
