version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./.persist/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
