server:
  port: ${PORT:8080}
  tomcat:
    accept-count: ${ACCEPT_THREADS:50}
    max-threads: ${MAX_THREADS:50}

---
management:
  endpoint:
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
      threshold: 100MB
  metrics:
    tags:
      host: ${HOSTNAME:localhost}
    export:
      prometheus:
        enabled: true
    web:
      client:
        request:
          autotime:
            enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

---

spring:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        generate_statistics: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/test}
    hikari:
      auto-commit: false
      connection-timeout: ${CONNECTION_TIMEOUT:10000}
      idle-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: ${MAX_CONN_POOL:50}
      minimum-idle: 10
      pool-name: ${HOSTNAME:dbPool}
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: ${DB_USER:test}
      username: ${DB_PASS:test}

---
logging:
  level:
    root: INFO
#    org:
#      hibernate:
#        stat: DEBUG
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: DEBUG
